<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Try it Yourself</name>
   <tag></tag>
   <elementGuidId>c3810de0-ebb5-4e21-9977-e1cb40eeb072</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.w3-btn.w3-margin-bottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be734bd0-20a4-4e4c-85fb-1061f245754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2dfdf67b-c5c5-4dc6-9d13-5caf523c7eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>tryit.asp?filename=tryjs_alert</value>
      <webElementGuid>09b01cf9-78c3-4044-b1df-25042e102842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w3-btn w3-margin-bottom</value>
      <webElementGuid>39f63633-022b-4933-90ee-9602e42f172b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Try it Yourself »</value>
      <webElementGuid>5479f5e6-715a-46d7-8ba6-f165fa016fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;w3-example&quot;]/a[@class=&quot;w3-btn w3-margin-bottom&quot;]</value>
      <webElementGuid>2b8ef9ac-676b-4a83-8259-586099404a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]/a</value>
      <webElementGuid>6fb0ede6-9c72-4d38-bf0c-e05eb62f50fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Try it Yourself »')]</value>
      <webElementGuid>a8730cef-7b7d-4c97-8fd2-d604ee913213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'I am an alert box!', '&quot;', '')])[1]/following::a[1]</value>
      <webElementGuid>1dda92e0-9744-4b66-b986-37c5ed7736d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm Box'])[1]/preceding::a[1]</value>
      <webElementGuid>8490a8a7-8d46-41ee-bd22-9445bf6e89c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='true'])[1]/preceding::a[1]</value>
      <webElementGuid>6bde87c8-e3ae-46c9-991d-3d459e0f8e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Try it Yourself »']/parent::*</value>
      <webElementGuid>9d152423-2a23-4dcb-91d5-ebcc60651456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'tryit.asp?filename=tryjs_alert')]</value>
      <webElementGuid>42a179e6-9612-47eb-86d8-d1a9f2b3b6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[4]/a</value>
      <webElementGuid>f3bd718a-9ec2-455d-98b0-35be6db5aab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'tryit.asp?filename=tryjs_alert' and (text() = 'Try it Yourself »' or . = 'Try it Yourself »')]</value>
      <webElementGuid>8ec6f3a1-c36d-4f2b-b130-b6716c197045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
