<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User_terms</name>
   <tag></tag>
   <elementGuidId>a740fe1b-e535-4bff-804b-9b619d5a7bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='terms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#terms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>970c810c-eafc-4d05-87b8-d69d16016b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>ac69f59c-5d95-410e-a4fb-3b50f122171c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>terms</value>
      <webElementGuid>0b878433-8029-4deb-9ab7-2286124a5076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c4f12c39-6917-499c-b3e3-0fad21d7cf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;terms&quot;)</value>
      <webElementGuid>de0e33b6-76fc-40fa-b7d6-0417835511a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='terms']</value>
      <webElementGuid>a2caed82-4925-44c6-b51d-ab1b8c5a6a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div[6]/label/span/input</value>
      <webElementGuid>2782a16d-75ce-4fe8-9556-aea2ebc6192d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>f4f7f325-6e7e-4515-8c30-6cae439fa8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'terms' and @name = 'terms' and @type = 'checkbox']</value>
      <webElementGuid>4d992787-4a58-4998-b765-8a1f364f1af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
