<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Checkbox 3(38.00)_option223</name>
   <tag></tag>
   <elementGuidId>2b04483f-9733-4600-b8c4-b53f4e1c17d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-option-value-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-option-value-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f11ca14c-971d-493a-946d-347bc6c0ca5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>92032bb6-207b-4cf9-aed3-4a64a5e29a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option[223][]</value>
      <webElementGuid>77bef307-f34b-4166-8d67-c7e320baaeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>7ce8315c-da55-4879-9bf5-e91e30d98650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-option-value-11</value>
      <webElementGuid>abc29ae0-ed77-4470-b5e3-6408d4f83322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c9ac4f25-0b1e-4754-95f8-51868044d08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-option-value-11&quot;)</value>
      <webElementGuid>1eea4824-75e4-44c0-8831-1d90486b9781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-option-value-11']</value>
      <webElementGuid>de9ba77e-5059-4f14-ae06-7c4f83f728d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-option-223']/div[4]/input</value>
      <webElementGuid>e6698d73-0cc3-4b82-8721-3b83539f066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>090648d9-08bd-493c-a933-bb5892a391fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'option[223][]' and @id = 'input-option-value-11']</value>
      <webElementGuid>b32075ea-336b-4fd6-8336-92cd4e142613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
