<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text_option208</name>
   <tag></tag>
   <elementGuidId>9c9034d0-20ee-47d0-bbb2-4017095d2a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-option-208</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-option-208']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b2f39e1-b5c6-4bb6-970b-ec3cc4a66035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>423ae960-85f5-47a4-adbb-0e9d06fdb2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option[208]</value>
      <webElementGuid>d44cc58e-682a-425c-91a1-fa440752423d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>0b4a9437-360e-4922-a6ed-06250a856533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Text</value>
      <webElementGuid>c1ad3106-0806-4875-8578-0c2daebb4422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-option-208</value>
      <webElementGuid>983f7ca2-85e6-4930-bdf9-cb2061e2beef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3a2af7e5-0a77-44de-ba35-f1bbc2997eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-option-208&quot;)</value>
      <webElementGuid>5e4aaf17-b5eb-480c-85be-fbb8d5c76fcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-option-208']</value>
      <webElementGuid>fad1fa8c-7898-4e76-b1b8-2ccb1625d9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-product']/div/div[3]/input</value>
      <webElementGuid>dcaceadb-48c2-4d43-9a38-51c084c0ebd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ca006353-a51a-457a-9801-bc14b11cce8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'option[208]' and @placeholder = 'Text' and @id = 'input-option-208']</value>
      <webElementGuid>138efeb1-fb5f-40e2-8aba-4969d1559ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
