<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio_option218</name>
   <tag></tag>
   <elementGuidId>d02d21c8-0e97-4579-b905-20838e191a54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-option-value-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-option-value-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee561b5b-2bd6-4620-8131-df3939218bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4daf3b84-17b4-4f0d-8cf0-f0277422b3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option[218]</value>
      <webElementGuid>de198fef-78c8-45bd-a408-9a08cdbc13aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>f77d5474-96b1-4446-85e1-f2760be01e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-option-value-5</value>
      <webElementGuid>8fd3b591-efed-45d6-b068-5a4f9b40502c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>e9e3574d-f039-42d2-983c-772e9d86b6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-option-value-5&quot;)</value>
      <webElementGuid>e3bd0f2a-0ab1-4014-8085-27b0c5aadbc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-option-value-5']</value>
      <webElementGuid>8a9e3622-2f53-4cd3-b8f7-7f46aa6726d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-option-218']/div/input</value>
      <webElementGuid>4603f03b-4efa-4f57-b829-2e93c19f07f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/input</value>
      <webElementGuid>722d911a-4866-45f5-9749-8f315b310dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'option[218]' and @id = 'input-option-value-5']</value>
      <webElementGuid>47261f94-c76d-4494-a6ef-15999930e184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
