<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Textarea_option209</name>
   <tag></tag>
   <elementGuidId>84de24a7-3785-4d20-9e39-b99c28d48356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-option-209</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='input-option-209']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4be18d16-c621-41af-9a94-64d6cba346ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option[209]</value>
      <webElementGuid>9dad99e2-5b98-4b1a-9636-03085761b6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bb68426d-aaaf-42f7-83fe-d06b169eca0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Textarea</value>
      <webElementGuid>6f07eb0d-0e6e-4a53-a680-760360e87600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-option-209</value>
      <webElementGuid>9860faf5-1f14-4d28-965a-6ca3e29b88fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f4985bbb-62a8-477b-b0b1-ea0a94a0e352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-option-209&quot;)</value>
      <webElementGuid>dc3c780d-3770-4d35-8ee0-ec1b6b329627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='input-option-209']</value>
      <webElementGuid>da589aa7-9f77-471b-99bf-325740a3eefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-product']/div/div[5]/textarea</value>
      <webElementGuid>a67db89e-97bb-473e-9ce1-59d4a41906be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3ec75603-a8b6-4e33-a24e-c2735854ddb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'option[209]' and @placeholder = 'Textarea' and @id = 'input-option-209']</value>
      <webElementGuid>478ac67e-d518-4023-94d1-14aa88ec55c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
