<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Male                        Female</name>
   <tag></tag>
   <elementGuidId>52905d95-691d-4345-848f-bbeb6b9180d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='exampleFormControlSelect1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#exampleFormControlSelect1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2b321ba3-f17c-402b-ad48-fab172937f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6f51df77-7fb2-4be3-b8e1-2bb924ac9c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleFormControlSelect1</value>
      <webElementGuid>808a33ae-328d-4f8b-8255-d97230b48575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Male
                        Female
                      </value>
      <webElementGuid>2605c4ef-2587-412d-a3e3-9f3d33b01207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleFormControlSelect1&quot;)</value>
      <webElementGuid>fe4c7223-8dad-4b86-aa21-c25793840db5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='exampleFormControlSelect1']</value>
      <webElementGuid>fd3cc155-4d73-444b-9a8c-327e07971716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::select[1]</value>
      <webElementGuid>d825ea62-ba47-480d-9ba4-a861d6cf6004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check me out if you Love IceCreams!'])[1]/following::select[1]</value>
      <webElementGuid>bb072200-f458-494e-9acf-e9c03276d0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status:'])[1]/preceding::select[1]</value>
      <webElementGuid>dd4f1760-6d60-4c0a-9416-a5968eefec32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[1]</value>
      <webElementGuid>4020b5a4-09c3-4ab8-a706-d3862bf3bd5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0ffc5fb8-8bba-4f6e-b920-3b262efc081a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'exampleFormControlSelect1' and (text() = '
                        Male
                        Female
                      ' or . = '
                        Male
                        Female
                      ')]</value>
      <webElementGuid>7366db29-9dab-4390-959b-d3782825ac72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
