<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Run_google_ads_iframe_22152718,16833_8cc2f2</name>
   <tag></tag>
   <elementGuidId>655a4f7a-f449-4f36-af67-ba807d5bb9c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>265a57de-3c47-4136-b6bb-2ffa84c4246d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0</value>
      <webElementGuid>7f8fe7e6-65a1-4a36-8341-e210a5d730f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0</value>
      <webElementGuid>9475750c-0aed-49f6-9320-a1b4ca0d3f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>3rd party ad content</value>
      <webElementGuid>7b327cbe-afac-440f-92b5-69d0da0d7f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>42ef3edf-854d-4f5a-904a-e6f1f9feffa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9e33dc55-444b-43bb-8efa-ca0c7d8c248f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>a9e83f52-b3b3-40e1-bc5e-24a8b3ab6df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9212a3b-0411-43a1-b20f-37022b56f01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1e44462-469b-4303-8974-99a7ce682ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>23a8a912-9015-4251-b89a-e435f5dab562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>ee43c4ba-3fc0-4b3f-94a9-fb8dad435d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>aa6eb34b-9959-44f5-9027-4e292f649b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c06b5a21-7c96-46b0-a125-aae8543e11ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-google-container-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eaf82ce0-f268-4cea-bd66-fb3d9ec48260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-load-complete</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29c98bca-f5cf-4665-b344-9e3a75ac39c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0&quot;)</value>
      <webElementGuid>a9a3ba0f-3092-41ac-84bf-d4556bcaf145</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0']</value>
      <webElementGuid>58470a58-8d10-4f39-8f5e-a8636ea7a09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0__container__']/iframe</value>
      <webElementGuid>dd87134a-00b3-470c-b291-d6cf1f017582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>b48138c7-a292-4051-b216-623bba022d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0' and @name = 'google_ads_iframe_/22152718,16833175/sws-hb//w3schools.com//try_it_leaderboard_0' and @title = '3rd party ad content']</value>
      <webElementGuid>0864df5d-073c-4b4e-a678-789d8b63563a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
