<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeamznad708456</name>
   <tag></tag>
   <elementGuidId>7a23e483-24f8-43ce-a246-11c1cf115776</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amznad708456</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='amznad708456']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>25b841f7-f3d9-4bbf-b4be-5c69d62749e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>20e061a1-0951-4eb9-aa5e-bd5056d8b347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea0a2b1a-e3dc-441f-91e5-f747cb648dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2ac5147b-d4a3-45e6-943c-2ca9166132e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fcb7f35f-f959-4e76-985c-1d453e0ffc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amznad708456</value>
      <webElementGuid>a02d4f87-2afc-4047-be20-1d0469f54a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation</value>
      <webElementGuid>418fcff8-3030-4e1b-89b3-10592c210460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://aax-fe-sin.amazon-adsystem.com/e/dtb/admi?b=JN3c7HDtLNVwyAIcp_urbpwAAAGKaLQ8AQUAAA9XAQBhcHNfdHhuX2JpZDEgICBhcHNfdHhuX2ltcDEgICB7e5i-&amp;rnd=2833145135191693973757694&amp;pp=iskwzk&amp;p=v7kqv4&amp;crid=556_16_484541008&amp;ep=%7B%22ce%22%3A%221%22%7D</value>
      <webElementGuid>b15cac47-cec4-48cb-a8fd-6eb801f3ce1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amznad708456&quot;)</value>
      <webElementGuid>99bb9a43-1553-4f04-86ff-d9711327e14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alert/Page_W3Schools Tryit Editor/iframe_Run_google_ads_iframe_22152718,16833_8cc2f2</value>
      <webElementGuid>0f8f7ec2-9cea-4afd-81de-46f831c47cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='amznad708456']</value>
      <webElementGuid>f24f09c0-8c64-4488-85dc-ce514a54c6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b6d58f05-07d7-48df-9adf-90ce5af2da2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'amznad708456' and @src = 'https://aax-fe-sin.amazon-adsystem.com/e/dtb/admi?b=JN3c7HDtLNVwyAIcp_urbpwAAAGKaLQ8AQUAAA9XAQBhcHNfdHhuX2JpZDEgICBhcHNfdHhuX2ltcDEgICB7e5i-&amp;rnd=2833145135191693973757694&amp;pp=iskwzk&amp;p=v7kqv4&amp;crid=556_16_484541008&amp;ep=%7B%22ce%22%3A%221%22%7D']</value>
      <webElementGuid>50801e45-5b39-4c12-8e5e-19edb73b6698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
