<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>f2c3888e-0e41-4508-8b2f-8442c3a58713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Advertisement&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='img_anch_CPnkooGQlYEDFVmkZgIdH98C4A']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b988b80a-d832-49c4-afeb-70fa4e8e5428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s0.2mdn.net/simgad/5461902895227863858</value>
      <webElementGuid>f5918d5d-8600-4acf-af26-f0c32889f838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Advertisement</value>
      <webElementGuid>df154dc3-11c4-454b-b6f8-3e63ddaddc91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11c38554-82db-4bff-b0e7-1762054a0f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>728</value>
      <webElementGuid>b997cb4c-0f5f-4848-b4db-0fb3eb875175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>1d0f643f-8912-4952-ae6a-6a4c528625e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_anch_CPnkooGQlYEDFVmkZgIdH98C4A&quot;)/img[1]</value>
      <webElementGuid>65a9926b-1d98-4e13-91ed-35ba091661eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Alert/Page_W3Schools Tryit Editor/iframeamznad708456</value>
      <webElementGuid>40809183-4de8-4d4c-867e-5845de3bf555</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='img_anch_CPnkooGQlYEDFVmkZgIdH98C4A']/img</value>
      <webElementGuid>687b1c70-4775-4765-a6cd-1f29ae39d8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Advertisement']</value>
      <webElementGuid>97d976db-56d5-4724-8b97-ffebfa0e9554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>5ebed0be-3c2e-4a14-bb45-c6aa87ad39b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s0.2mdn.net/simgad/5461902895227863858' and @alt = 'Advertisement']</value>
      <webElementGuid>98839d08-3e64-4774-bfe3-c762cf739501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
