<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium.concurrent</name>
   <tag></tag>
   <elementGuidId>473a44df-4484-401c-b75c-9b6e88a08e18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='all-packages-table']/div[2]/div[17]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d93b176-3c83-4645-b0ea-591190e274c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/concurrent/package-summary.html</value>
      <webElementGuid>12bd4f4b-286c-4de2-93d5-6ef17ca279d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.concurrent</value>
      <webElementGuid>a588de4e-216c-4968-a301-18385054d4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-packages-table&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first odd-row-color all-packages-table all-packages-table-tab1&quot;]/a[1]</value>
      <webElementGuid>c15827a5-fc7c-4bd5-b7df-6d957af267e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-packages-table']/div[2]/div[17]/a</value>
      <webElementGuid>bee63776-7476-428c-9f88-af2c6ecd54ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium.concurrent')]</value>
      <webElementGuid>3d987106-dc89-4e81-98b3-7894c875d850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mechanisms to configure and run selenium via the command line.'])[1]/following::a[1]</value>
      <webElementGuid>f7c5609b-9afc-4fb4-acb0-675670327269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.cli'])[1]/following::a[1]</value>
      <webElementGuid>1a9d98f8-93f5-4893-9933-81d4f6a4774d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools'])[1]/preceding::a[1]</value>
      <webElementGuid>c3ec4d83-4c28-480d-8656-476bec303211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools.events'])[1]/preceding::a[2]</value>
      <webElementGuid>2276fb27-2a73-43f0-8c9f-f458b112091a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium.concurrent']/parent::*</value>
      <webElementGuid>7410d745-9bbc-4d1f-8261-fd5ca826c9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/concurrent/package-summary.html')]</value>
      <webElementGuid>97c84295-ad9b-42c6-a45e-8c236f61996a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/a</value>
      <webElementGuid>1419be8c-7bda-4204-a58d-fb039d2f6ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/concurrent/package-summary.html' and (text() = 'org.openqa.selenium.concurrent' or . = 'org.openqa.selenium.concurrent')]</value>
      <webElementGuid>9d01eefc-f7bb-4cce-8cf0-b8534bacafae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
